#ifndef _INCLUDE_VERSION_INFORMATION_H_
#define _INCLUDE_VERSION_INFORMATION_H_

/**
 * @file Contains version information.
 * @brief This file will redirect to an autogenerated version if being compiled via
 * the build scripts.
 */

#if defined SM_GENERATED_BUILD
#include "version_auto.h"
#else

#ifndef SM_GENERATED_BUILD
#undef BINARY_NAME
#define BINARY_NAME "sampleext.ext.dll\0"
#endif

#define BUILD_TAG		"-manual"
#define BUILD_UNIQUEID	"[MANUAL BUILD]"
#define VERSION_STRING		"1.0.0"
#define FULL_VERSION		VERSION_STRING BUILD_TAG
#define VERSION_FILE		0,0,0,0

#endif

#endif /* _INCLUDE_VERSION_INFORMATION_H_ */
