#ifndef _INCLUDE_VERSION_INFORMATION_H_
#define _INCLUDE_VERSION_INFORMATION_H_

/**
 * @file Contains version information.
 * @brief This file will redirect to an autogenerated version if being compiled via
 * the build scripts.
 */

#if defined EXT_GENERATED_BUILD
#include "version_auto.h"
#else

#ifndef EXT_GENERATED_BUILD
#undef BINARY_NAME
#define BINARY_NAME "sampleext.ext.dll\0"
#endif

#define EXT_BUILD_TAG		"-manual"
#define EXT_BUILD_UNIQUEID	"[MANUAL BUILD]"
#define EXT_VERSION_STRING	"1.0.0"
#define EXT_FULL_VERSION	EXT_VERSION_STRING EXT_BUILD_TAG
#define EXT_VERSION_FILE	1,0,0,0

#endif

#endif /* _INCLUDE_VERSION_INFORMATION_H_ */
